#!/usr/bin/env bash
# Script to send a file from client to the server

if [ "$#" -lt 5 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit(1)
fi

PATH_TO_FILE = $1
IP = $2
USERNAME = $3
PATH_TO_SSH_KEY = $4

scp PATH_TO_SSH_KEY PATH_TO_FILE USERNAME@IP:~
