#!/usr/bin/env bash
# Script to configure a server to install nginx web_server

apt-get update
apt-get -y install nginx

#ufw allow "Nginx HTTP"

echo "Hello World!" > /var/www/html/index.html

service nginx start
