#!/usr/bin/env bash
# Script to configure a server to install nginx web_server

sudo apt-get update
sudo apt-get -y install nginx

# sudo rm /etc/nginx/sites-enabled/default

sudo rm /var/www/html/index.nginx-debian.html

cat << EOL > /etc/nginx/sites-enabled/default
sever {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	location / {
		return 200 'Hello World!';
	}
	location / {
		try_files $uri $uri/ =404;
	}

	sever_name_;
}"
EOL
sudo service nginx restart
