#!/usr/bin/env bash
# Script to configure an nginx server to redirect to another page

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

#echo 'Hello World!' > /var/www/html/index.nginx-debian.html

#service start nginx

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    location = / {
        return 200 "Hello World!";
    }

    rewrite ^/redirect_me/(.*)$ https://www.youtube.com/watch?v=lE-qjOzwk3s permanent;
}
EOF

sudo service nginx restart
