#!/usr/bin/env bash
# Scripr to configure web_02 to be exact as web_02.

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx

ufw allow "Nginx HTTP"

add_on=24
AVALABLE_D="/etc/nginx/sites-available/default"
ENABLED_D="/etc/nginx/sites-enabled/default"
add="\tadd_header X-Served-By $hostname"
sed -i "${add_on}s~.*~${add}~" $AVAILABLE_D
sed -i "${add_on}s~.*~${add}~" $ENABLED_D

service nginx start
