#!/usr/bin/env bash
# Scripr to configure web_02 to be exact as web_02.

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx

ufw allow "Nginx HTTP"

add_on=24
AVALLABLE_D="/etc/nginx/sites_availlable/default"
ENABLED_D="/etc/nginx/sites_enabled/default"
add="\tadd_header $hostname"
sed -i "${add_on}s~.*~${add}~" $AVAILLABLE_D
sed -i "${add_on}s~.*~${add}~" $ENABLED_D

service nginx start
