#!/usr/bin/env bash
# Script to install and config the load balancer

apt-get -y update
apt-get -y install haproxy

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
backend web-backend
   bind 0:80
      default_backend server_backend

backend server-backend
   balance roundrobin
   server 306152-web-01 18.235.255.111 check
   server 306152-web-02 18.204.14.87 check
EOF

service haproxy start
