#!/usr/bin/env bash
# Script to install and config the load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy

echo '
frontend front
       bind 0:80
               default_backend server_backend

backend server_backend
       balance roundrobin
       server studentid-servernumber serverIp:80 check
       server studentid-servernumber serverIp:80 check
' >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
