#!/usr/bin/env bash
# Script to install and config the load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

echo '' >> /etc/haproxy/haproxy.cfg
echo '' >> /etc/haproxy/haproxy.cfg

file='/etc/haproxy/haproxy.cfg'
line=36
text='frontend Mega\n'
sed -i "${line}s~.*~${text}~" $file

line2=37
text2='\tbind *:80\n\tdefault_backend MegaBackend'
sed -i "${line2}s~.*~${text2}~" $file

echo '' >> /etc/haproxy/haproxy.cfg
# echo '' >> /etc/haproxy/haproxy.cfg
line3=40
text3='backend MegaBackend\n\tbalance roundrobin\n'

sed -i "${line3}s~.*~${text3}~" $file

line4=42
text4='\tserver  306152-web-01 18.235.255.111:80 check\n'

sed -i "${line4}s~.*~${text4}~" $file

line5=43
text5='\tserver 306152-web-02 18.204.14.87:80 check'

sed -i "${line5}s~.*~${text5}~" $file

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

service haproxy start
