#!/usr/bin/env bash
# Bash script to automate a server to listen to port 80
# of all the server’s active IPv4 IPs

sudo apt-get -y update
sudo apt-get -y install nginx

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart
