#!/usr/bin/env bash
# Script to automate nginx to listen to port 80 made short.
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginax.pid
