#!/usr/bin/env bash
# This script displays 12 hour clock
(( h="0" ))
(( m="1" ))
while [ $h -le "12" ]
do
	echo "Hour: $h"
	while [ $m -le "59" ]; do
		echo "$m"
		(( m = m+1 ))
	done
	(( m = "1" ))
	(( h = h+1 ))
done
