#!/usr/bin/env bash
# Script to loock for a file in current directory.
dir=$(pwd)
sch=""
for f in "$dir"/*; do
	if [ "$f" == "$dir"/school ]; then
		sch=$f
		break
	fi
done
if [ -n "$sch" ]; then
	echo "school file exists"
	if [ -s "$sch" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$sch" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
