#!/usr/bin/env bash
# Script to configure nginx to run as nginx user

if ! id -u nginx &>/dev/null; then
	sudo adduser --system --no-create-home --disabled-login --group nginx
fi

# Update Nginx configuration to run as the nginx user
# by replacing the first occurence of the "user " with "user nginx;"
# or if not found put it at the end of the file
if grep -q '^user ' /etc/nginx/nginx.conf; then
    sudo sed -i '0,/^user / s/^user .*/user nginx;/' /etc/nginx/nginx.conf
else
    sudo echo "user nginx;" >> /etc/nginx/nginx.conf
fi

# echo "user nginx;" > /etc/nginx/nginx.conf

sudo systemctl restart nginx
