#!/usr/bin/env bash
# Script to connect to 'ubuntu' server.

# cat ~/.ssh/id_rsa.pub | ssh ubuntu@34.239.107.43 "mkdir -p ~/.ssh && chmod 700 ~/.ssh && cat >>  ~/.ssh/authorized_keys"

ssh -i '~/.ssh/school' ubuntu@34.239.107.43
